baseURL       = "https://technotut.net/"
languageCode  = "ja-jp"
title         = "TechnoTUT"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 3
  [[menu.nav]]
    name    = "Docs"
    url     = "https://docs.technotut.net/"
    weight  = 4
  [[menu.nav]]
    name    = "Get in touch"
    url     = "https://twitter.com/ToyohashiTechno"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "TechnoTUT official Site"
  author = "TechnoTUT"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/USAg2Jl"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "https://twitter.com/ToyohashiTechno/"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "We’re TechnoTUT"
    tagline               = "DJ & VJ Club"
    primary_button        = "See Our Activity"
    primary_button_url    = "blog"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "https://twitter.com/ToyohashiTechno/"

  [params.portfolio]
    enable    = false
    title     = "OUR RECENT WORKS"
    subtitle  = "Crafting experiences and seeking to make the complex clear & beautiful."

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S PLAY TOGETHER"
    primary_button      = "See Activity"
    primary_button_url  = "blog"
    secondary_button    = "Contact"
    secondary_button_url = "https://twitter.com/ToyohashiTechno"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Address"
      address = "愛知県豊橋市<br>天伯町雲雀ヶ丘１－１<br> 豊橋技術科学大学<br> クラブハウス ２階"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Docs"
          url  = "https://docs.techno.tut-club.net/"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "https://twitter.com/ToyohashiTechno"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Twitter"
          url  = "https://twitter.com/ToyohashiTechno"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/technotut/"
        [[params.footer.social.link]]
          name = "GitHub"
          url  = "https://github.com/TechnoTUT/"
      # Footer Service
      [params.footer.service]
        title       = "We are TechnoTUT:"
        description = "toyohashitechno@<br> ※アドレスの末尾に「gmail.com」を補完してください"